version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shop
    healthcheck:
      test: "pg_isready -q U postgres"
  flyway:
    image: flyway/flyway:latest
    container_name: migrations
    command: -url=jdbc:postgresql://postgres/shop -schemas=public -user=postgres -password=admin migrate
    volumes:
      - ../db/migrations:/flyway/sql
    depends_on:
      - postgres